spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/TravelPlanRepo
    username: root
    password: Mtkaflq159!
  jpa:
    hibernate:
      ddl-auto: update

decorator:
  datasource:
    p6spy:
      enable-logging: true

file:
  profileImg: \C:\Users\Hong\IdeaProjects\Codestates\study\TravelPlanRepo\img\profileImg\
  boardImg: \C:\Users\Hong\IdeaProjects\Codestates\study\TravelPlanRepo\img\profileImg\
  itineraryImg: \C:\Users\Hong\IdeaProjects\Codestates\study\TravelPlanRepo\img\profileImg\

env: local
logTracer: true